/*==============================================================================
Copyright (c) 2017 PTC Inc. All Rights Reserved.

Copyright (c) 2010-2014 Qualcomm Connected Experiences, Inc.
All Rights Reserved.
Confidential and Proprietary - Protected under copyright and other laws.
==============================================================================*/

using UnityEngine;
using Vuforia;
using UnityEngine.UI;
using System;

/// <summary>
/// A custom handler that implements the ITrackableEventHandler interface.
///
/// Changes made to this file could be overwritten when upgrading the Vuforia version.
/// When implementing custom event handler behavior, consider inheriting from this class instead.
/// </summary>
public class MarkerEventHandler : MonoBehaviour, ITrackableEventHandler
{

    #region PROTECTED_MEMBER_VARIABLES

    protected TrackableBehaviour mTrackableBehaviour;
    protected TrackableBehaviour.Status m_PreviousStatus;
    protected TrackableBehaviour.Status m_NewStatus;
    public TextMesh output;
    public string thisMarkersName="";

    bool thisMarkerHasBeenFound=false;
    GameStateController myController;
    
    #endregion // PROTECTED_MEMBER_VARIABLES

    #region UNITY_MONOBEHAVIOUR_METHODS


    protected virtual void Start()
    {
        mTrackableBehaviour = GetComponent<TrackableBehaviour>();
        if (mTrackableBehaviour)
            mTrackableBehaviour.RegisterTrackableEventHandler(this);
        output.text="start";
        myController=(GameStateController)FindObjectOfType(typeof(GameStateController));
    }

    protected virtual void OnDestroy()
    {
        if (mTrackableBehaviour)
            mTrackableBehaviour.UnregisterTrackableEventHandler(this);
    }

    #endregion // UNITY_MONOBEHAVIOUR_METHODS

    #region PUBLIC_METHODS

    /// <summary>
    ///     Implementation of the ITrackableEventHandler function called when the
    ///     tracking state changes.
    /// </summary>

    //avoid editing this function; just edit the OnTrackingFound/Lost ones
    public void OnTrackableStateChanged(
        TrackableBehaviour.Status previousStatus,
        TrackableBehaviour.Status newStatus)
    {
        m_PreviousStatus = previousStatus;
        m_NewStatus = newStatus;

        if (newStatus == TrackableBehaviour.Status.DETECTED ||
            newStatus == TrackableBehaviour.Status.TRACKED ||
            newStatus == TrackableBehaviour.Status.EXTENDED_TRACKED)
        {
            OnTrackingFound();
        
        }
        else if (previousStatus == TrackableBehaviour.Status.TRACKED &&
                 newStatus == TrackableBehaviour.Status.NO_POSE)
        {
            
            //OnTrackingLost();
        }
        else
        {
            // For combo of previousStatus=UNKNOWN + newStatus=UNKNOWN|NOT_FOUND
            // Vuforia is starting, but tracking has not been lost or found yet
            // Call OnTrackingLost() to hide the augmentations
            //output.text="nothing " + mTrackableBehaviour.TrackableName + " lost";
            //OnTrackingLost();
        }
    }

    #endregion // PUBLIC_METHODS

    #region PROTECTED_METHODS

    protected virtual void OnTrackingFound()
    {
        
        var rendererComponents = GetComponentsInChildren<Renderer>(true);
        var colliderComponents = GetComponentsInChildren<Collider>(true);
        var canvasComponents = GetComponentsInChildren<Canvas>(true);

        Debug.Log("Trackable " + mTrackableBehaviour.TrackableName);
        output.text="Trackable " + mTrackableBehaviour.TrackableName +": "+ "..."+ ((float)(Math.Truncate((double)gameObject.transform.up.x*100.0) / 100.0))+" "+ ((float)(Math.Truncate((double)gameObject.transform.up.y*100.0) / 100.0))+" "+ ((float)(Math.Truncate((double)gameObject.transform.up.z*100.0) / 100.0))+ ((float)(Math.Truncate((double)gameObject.transform.right.x*100.0) / 100.0))+" "+ ((float)(Math.Truncate((double)gameObject.transform.right.y*100.0) / 100.0))+" "+ ((float)(Math.Truncate((double)gameObject.transform.right.z*100.0) / 100.0))+"*****"+Vector3.Angle(new Vector3(0,0,-1),gameObject.transform.up);


        thisMarkerHasBeenFound=true; //this would be used for a dynamic object, i guess. not really useful right now

        //since we now know WHERE the marker is, and it shouldn't move, then we shouldn't need to track it anymore. this won't be a fair assumption with opening doors, but we can
        //assume a static double door like in nick's lab for now.
        //something that can be done in the future is increasing the positional confidence over a few frames instead of using 1 frame like we are now.
        if (mTrackableBehaviour)
            mTrackableBehaviour.UnregisterTrackableEventHandler(this);
        
        //ask controller to register this marker
        thisMarkersName=mTrackableBehaviour.TrackableName;
        myController.updateMarkerTrackedStated(this);
        

        // Enable rendering:
        foreach (var component in rendererComponents)
            component.enabled = true;

        // Enable colliders:
        foreach (var component in colliderComponents)
            component.enabled = true;

        // Enable canvas':
        foreach (var component in canvasComponents)
            component.enabled = true;
    }

//not useful to us
    /*
    protected virtual void OnTrackingLost()
    {
        var rendererComponents = GetComponentsInChildren<Renderer>(true);
        var colliderComponents = GetComponentsInChildren<Collider>(true);
        var canvasComponents = GetComponentsInChildren<Canvas>(true);

        Debug.Log("Trackable " + mTrackableBehaviour.TrackableName + " lost");
        output.text="Trackable " + mTrackableBehaviour.TrackableName + " lost";

        // Disable rendering:
        foreach (var component in rendererComponents)
            component.enabled = false;

        // Disable colliders:
        foreach (var component in colliderComponents)
            component.enabled = false;

        // Disable canvas':
        foreach (var component in canvasComponents)
            component.enabled = false;
    }
    */

    #endregion // PROTECTED_METHODS
}
